# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name': 'Odoo All in One Dashboard',
    'version': '12.0.4.0',
    'summary': 'Manage your Sale, Purchase, Invoice and Inventory from only one screen with Stylish Graphs.',
    'category': 'Dashboard',
    'depends': ['base_setup','sale_management'],
    'data': [
        "security/dashboard_security.xml",
        "security/ir.model.access.csv",
        "views/dashboard_views.xml",
        "views/board_config.xml",

        "wizards/move_to_board_views.xml",

        "data/dashboard_data.xml",
        "views/assets.xml"
    ],
    'images': ['static/description/all_in_one_dashboard.gif'],
    'demo': [],
    'license': 'OPL-1',
    'qweb': ['static/src/xml/dashboard.backend.xml',
             'static/src/xml/color_widget.xml'],
    "author": "Teqstars",
    "website": "https://teqstars.com",
    'support': 'info@teqstars.com',
    'maintainer': 'Teqstars',
    "description": """Manage your Sale, Purchase, Invoice and Inventory from only one screen with Stylish Graphs
        Odoo Dashboard, 
        Dashboard,
        Odoo apps,
        Dashboard app,
        HR Dashboard,
        Sales Dashboard, 
        inventory Dashboard, 
        Lead Dashboard, 
        Opportunity Dashboard, 
        CRM Dashboard,
	    POS,
	    POS Dashboard,
	    Connectors,
	    Web Dynamic,
	    Report Import/Export,
	    Date Filter,
	    HR,
	    Sales,
	    Theme,
	    Tile Dashboard,
	    Dashboard Widgets,
	    Dashboard Manager,
	    Debranding,
	    Customize Dashboard,
	    Graph Dashboard,
	    Charts Dashboard,
	    Invoice Dashboard,
	    Project management
	    Odoo All in One Dashboard,
	    POS All In One Futures,
	    Gantt Native Web view,
	    Dashboard Ninja,
	    Nearby Warehouse,
	    good dashboard,
	    Odoo best Dashboard,
	    best odoo dashboard,
	    best dashboard,
	    Connector,
	    Amazon Connector,
	    Ebay Connector,
	    Shopify Connector,
	    woocommerce Connector,
	    """,
    'installable': True,
    'application': True,
    'live_test_url':'https://demo.teqstars.com/web?db=dashboarddemo',
    'auto_install': False,
    "price": "99.99",
    "currency": "EUR",
}
